services:
  postgres:
    image: postgres:17.5
    container_name: saas-db-container
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-saas-app-db}
      PGDATA: /var/lib/postgresql/data/data
    ports:
      - "${DB_PORT:-5434}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/data
    networks:
        - saas-app-container-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
networks:
  saas-app-container-network:
    driver: bridge