package org.ziad.mutlitenantsaas.entity;

import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.SuperBuilder;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.Instant;

import static jakarta.persistence.EnumType.STRING;

/**
 * Represents a company (tenant) registered on the SaaS platform.
 *
 * <p>Lifecycle:
 * <ol>
 *   <li>A company self-registers via {@code POST /v1/auth/register} — status is set to
 *       {@link TenantStatus#PENDING}.</li>
 *   <li>A platform admin approves the tenant — status transitions to
 *       {@link TenantStatus#ACTIVE} and a dedicated PostgreSQL schema
 *       ({@code tenant_<companyCode>}) is provisioned by {@link org.ziad.mutlitenantsaas.service.ProvisioningService}.</li>
 *   <li>The admin can later {@code SUSPEND} or {@code DEACTIVATE} the tenant.</li>
 * </ol>
 *
 * <p>The {@code adminPassword} field stores the BCrypt-hashed password of the
 * initial company-admin user. It is used only during tenant approval to seed the
 * admin {@link User} record and should not be returned in API responses.
 */
@Getter
@Setter
@SuperBuilder
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "tenants")
@EntityListeners(AuditingEntityListener.class)
public class Tenant {

    /** UUID primary key generated by the database engine. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(nullable = false)
    private String id;

    /** Timestamp of record creation; set once and never updated. */
    @CreatedDate
    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed on every {@code UPDATE}. */
    @LastModifiedDate
    @Column(nullable = false)
    private Instant updatedAt;

    /**
     * Soft-delete flag. {@code true} means the record is logically deleted and should
     * be excluded from normal queries; {@code false} means it is active.
     */
    @Column(nullable = false)
    private Boolean deleted;

    /** Legal name of the company. */
    @Column(nullable = false)
    private String companyName;

    /**
     * Short unique alphanumeric slug for the company.
     * Used to name the tenant's PostgreSQL schema: {@code tenant_<companyCode>}.
     */
    @Column(nullable = false, unique = true)
    private String companyCode;

    /** Primary contact email address for the company. */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * Current lifecycle status of the tenant.
     * Defaults to {@link TenantStatus#PENDING} on registration.
     */
    @Enumerated(STRING)
    @Column(nullable = false)
    @Builder.Default
    private TenantStatus status = TenantStatus.PENDING;

    /** Full name of the initial admin user created during tenant approval. */
    @Column(nullable = false)
    private String adminFullName;

    /** Email address of the initial admin user. Must be unique across all users. */
    @Column(nullable = false, unique = true)
    private String adminEmail;

    /** Username of the initial admin user. Must be unique across all users. */
    @Column(nullable = false, unique = true)
    private String adminUsername;

    /**
     * BCrypt-hashed password of the initial admin user.
     * <strong>Never</strong> include this field in API responses.
     */
    @Column(nullable = false)
    private String adminPassword;

}