package org.ziad.mutlitenantsaas.common;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.SuperBuilder;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.Instant;

/**
 * Base JPA entity that all domain entities must extend.
 *
 * <p>Provides the following cross-cutting concerns automatically:
 * <ul>
 *   <li><b>Identity</b> — UUID primary key generated by the database.</li>
 *   <li><b>Auditing</b> — {@code createdAt}, {@code updatedAt}, {@code createdBy} and
 *       {@code updatedBy} are populated by Spring Data's {@link AuditingEntityListener}.
 *       Requires {@code @EnableJpaAuditing} on the application class.</li>
 *   <li><b>Soft-delete</b> — a {@code deleted} flag defaults to {@code false} on first
 *       persist; repositories should filter by {@code deleted = false} rather than issuing
 *       physical DELETEs.</li>
 * </ul>
 *
 * <p>Uses Lombok's {@code @SuperBuilder} so subclasses can participate in builder
 * inheritance without boilerplate.
 */
@Getter
@Setter
@SuperBuilder
@AllArgsConstructor
@NoArgsConstructor
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
public class AbstractEntity {

    /** UUID primary key generated by the database engine. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(nullable = false)
    private String id;

    /** Timestamp of record creation; set once and never updated. */
    @CreatedDate
    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed on every {@code UPDATE}. */
    @LastModifiedDate
    @Column(nullable = false)
    private Instant updatedAt;

    /** Principal (username / user ID) that created this record. */
    @CreatedBy
    @Column(nullable = false, updatable = false)
    private String createdBy;

    /** Principal (username / user ID) that last modified this record. */
    @LastModifiedBy
    @Column
    private String updatedBy;

    /**
     * Soft-delete flag. {@code true} means the record is logically deleted and should
     * be excluded from normal queries; {@code false} means it is active.
     */
    @Column(nullable = false)
    private Boolean deleted;

    /**
     * JPA lifecycle callback executed just before the entity is first persisted.
     * Initialises {@code deleted} to {@code false} if it has not already been set,
     * guaranteeing the column is never {@code NULL} on insert.
     */
    @PrePersist
    private void onCreate() {
        if (deleted == null) deleted = false;
    }
}
